export enum ORDER_ACTIONS {
  SetCurrentOrder = '[Order/Service] Set Current Order',
  RemoveCurrentOrder = '[Order/Service] Remove Current Order',
  LoadOrder = '[Order/Service] Load Orders',
  AddOrder = '[Order/Service] Add Order',
  SetOrder = '[Order/Service] Set Order',
  UpsertOrder = '[Order/Service] Upsert Order',
  AddOrders = '[Order/Service] Add Orders',
  UpsertOrders = '[Order/Service] Upsert Orders',
  UpdateOrder = '[Order/Service] Update Order',
  UpdateOrders = '[Order/Service] Update Orders',
  MapOrder = '[Order/Service] Map Order',
  MapOrders = '[Order/Service] Map Order',
  DeleteOrder = '[Order/Service] Delete Order',
  DeleteOrders = '[Order/Service] Delete Orders',
  DeleteOrderByPredicate = '[Order/Service] Delete Order By Predicate',
  ClearOrders = '[Order/Service] Clear Orders',
  SetLoading = '[Order/Service] SetLoading',
}
