export enum PRODUCT_ACTIONS {
  SetCurrentProduct = '[Product/Service] Set Current Product',
  RemoveCurrentProduct = '[Product/Service] Remove Current Product',
  LoadProduct = '[Product/Service] Load Products',
  AddProduct = '[Product/Service] Add Product',
  SetProduct = '[Product/Service] Set Product',
  UpsertProduct = '[Product/Service] Upsert Product',
  AddProducts = '[Product/Service] Add Products',
  UpsertProducts = '[Product/Service] Upsert Products',
  UpdateProduct = '[Product/Service] Update Product',
  UpdateProducts = '[Product/Service] Update Products',
  MapProduct = '[Product/Service] Map Product',
  MapProducts = '[Product/Service] Map Product',
  DeleteProduct = '[Product/Service] Delete Product',
  DeleteProducts = '[Product/Service] Delete Products',
  DeleteProductByPredicate = '[Product/Service] Delete Product By Predicate',
  ClearProducts = '[Product/Service] Clear Products',
  SetLoading = '[Product/Service] SetLoading',
}
